# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bf5ac833eed795e1b0ff374b5bcb1650c8249bd48ff354a6737d500fa6d1beb947067c2ee11ca85ef1ad8d63b2b19b4d08a6cab51d23f3a23854f2294c351e5

test:
  secret_key_base: 651b15d4e94d4c0c63eb9606d621ff3dbea036d029b83f481b3789339a477d0af83162d5b624e9e84b3237809658dffd63b3cd6b8e5fbd56525ba8852461dcc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
